class Solution:
    def singleNonDuplicate(self, nums: list[int]) -> int:
        left, right = 0, len(nums) - 1
        while left <= right:
            mid = left + ((right - left) // 2)
            if ((mid - 1 < 0 or nums[mid - 1] != nums[mid]) and
                (mid + 1 == len(nums) or nums[mid] != nums[mid + 1])):
                return nums[mid]
            left_half_size = mid - 1 if nums[mid - 1] == nums[mid] else mid
            if left_half_size % 2:
                right = mid - 1
            else:
                left = mid + 1


"""Let me first make sure I understand the problem: I've got a sorted array where every number appears exactly twice except for one number that appears only once, and I need to find that single number, ideally faster than just scanning linearly. The key observation is that since the array is sorted, duplicates always sit right next to each other, so before the single element, every pair naturally lines up starting at an even index and ending at an odd index, like index zero and one, then two and three, and so on; but once you pass the single element, that alignment shifts and pairs start at odd indices instead. That shift in alignment is really a structural pattern I can binary search on, rather than needing any extra data structure — I just need to look at a middle index and figure out which side of that alignment break I'm on. So the approach is: I do a binary search where at each middle index, I first check if that middle element is actually the unique one, meaning it doesn't match its neighbor on either side, accounting for the edges of the array so I don't index out of bounds; if it is unique, I return it immediately. Otherwise, I need to figure out which half still has the correct pairing versus which half has the shifted pairing, so I check whether the middle element matches the one before it, and based on that I compute how large the properly-paired left half would be if the single element weren't in this half; if that size comes out odd, that tells me the break, and therefore the single element, must be somewhere in the left half, so I move my right boundary in, and if it's even, the pairing is still intact on the left, meaning the single element must be further right, so I move my left boundary forward instead. The subtle part here is that the parity of that left-half size is really just a stand-in for detecting which side of the array still has consistent even-index pairing, since that's what tells me where the disruption is. In terms of complexity, this is O(log n) time since I'm cutting the search space in half every iteration, and O(1) space since I'm only tracking a couple of index pointers throughout.

A linear scan checking every pair for a break in the pattern would work in O(n), but the array being sorted is a strong signal there's a faster option — specifically, since every element normally appears in a pair, the single element's position determines whether pairs before it start on even or odd indices, so at any index I can tell which side of the single element I'm on just by checking whether the current element's pair-partner sits where I'd expect for a 'no single element yet' region. Binary searching the midpoint, I check whether it's the lone unpaired element directly (its neighbors on both sides differ from it), and if not, I compute how large the left partition would be if the pairing pattern were undisturbed — an even-sized left partition means the single element must be to the right of mid, an odd-sized one means it's to the left, so I can eliminate half the search space each time. I chose binary search over a linear scan because sortedness plus the parity-of-partition-size property together enable true logarithmic time, whereas a linear scan discards that structure entirely, and this is directly analogous to Arrange Coins and Koko Eating Bananas in spirit — sortedness plus a provable monotonic/structural property unlocks binary search over a property that isn't obviously 'find a target value' at first glance. This runs in O(log n) time, since the search space is halved each iteration, and O(1) space, since only a few integer variables are tracked regardless of input size."""