class Solution:
    def minOperations(self, nums: list[int]) -> int:
        total_cost = 0
        for index in range(1, len(nums)):
            if nums[index] < nums[index - 1]:
                total_cost += nums[index - 1] - nums[index]
        return total_cost


"""Let me first make sure I understand the problem: I need to figure out the minimum cost to make the array non-decreasing, where I'm allowed to increase any element, and the cost of doing so is just how much I increase it by. The key observation is that I never actually need to reason globally about the whole array at once — since I only care about non-decreasing order, each element only ever needs to be compared against the element right before it, because if I bring an element up to at least match its predecessor, that's the cheapest possible fix, and I never need to touch anything further back. That tells me this doesn't need any extra data structure at all — I can just walk through the array once, comparing each pair of neighbors as I go. So the approach is: I keep a running total of the cost, and for every index starting from the second element, I check if the current number is smaller than the one right before it; if it is, that means I'd need to bump it up to match, so I add the difference between the previous element and the current one to my total cost, and if it's already greater than or equal, I don't need to do anything. One thing I'd point out is that I never actually modify the array itself, since I only care about tracking what the cost would be, not the resulting array, and comparing only to the immediate previous element is valid because any earlier bump I made would have already been accounted for in that previous element's value. In terms of complexity, this is O(n) time since it's a single pass through the array, and O(1) space since I'm just tracking a running total.

Since one operation can raise an entire contiguous subarray by the same amount x for a flat cost of x, regardless of how wide that subarray is, the cheapest way to fix any single 'drop' — a spot where a later element is smaller than the one before it — is to cover that drop with one operation sized exactly to close the gap, rather than paying anything proportional to range length; separate drops elsewhere in the array can each be closed independently without their costs compounding. That means the total minimum cost is just the sum of every individual drop size scanned left to right — wherever nums[i] < nums[i-1], that gap alone is the cost required to erase it, and I never need to actually construct or reason about which specific subarrays to choose, since only the total deficit matters for the answer, not the operations themselves. I chose this single-pass summing approach over simulating actual range-add operations because the flat per-operation cost (independent of width) means operation placement is a pure implementation detail with no effect on total cost — modeling it explicitly would add complexity without changing the answer. This runs in O(n) time, since the array is scanned exactly once, and O(1) space, since only a single running total is tracked regardless of input size."""