class Solution:
    def removeDuplicates(self, nums: list[int]) -> int:
        slow_pointer = 1

        for fast_pointer in range(1, len(nums)):
            if nums[fast_pointer] != nums[slow_pointer - 1]:
                nums[slow_pointer] = nums[fast_pointer]
                slow_pointer += 1

        return slow_pointer


"""Let me first make sure I understand the problem: I've got a sorted array and I need to remove the duplicates in place, so that each unique value appears only once, and I need to return the new length while modifying the original array in place rather than using extra space. The key observation is that since the array is already sorted, all duplicates of a value are guaranteed to sit right next to each other, so I never actually need to compare an element against everything I've seen — I only ever need to compare it against the last unique value I've placed so far. That tells me I don't need any extra data structure like a set to track what I've seen — I can just use two pointers directly on the array itself, one tracking where the next unique value should go, and one scanning ahead to find it. So the approach is: I start a slow pointer at index one, since the first element is trivially always unique, and I run a fast pointer through the rest of the array; for each element the fast pointer lands on, I compare it to the value just before the slow pointer, which represents the last unique value I've written so far, and if they're different, that means I've found a new unique value, so I copy it into the slow pointer's position and advance the slow pointer forward. If the values match, I just let the fast pointer keep moving without touching anything, since that's a duplicate I want to skip over. The reason I compare against nums[slow_pointer - 1] rather than the previous fast pointer position is that slow_pointer - 1 always reflects the last value I've actually kept, which is what defines a duplicate, not just whatever happened to be next to it in the original array. At the end, slow_pointer itself represents the count of unique elements, which is exactly what I need to return, and everything before that index in the array now holds the deduplicated values. In terms of complexity, this is O(n) time since both pointers only move forward through the array once, and O(1) space since I'm modifying the array in place with just two integer pointers.

Since the array is already sorted, every duplicate is guaranteed to sit immediately adjacent to its matches, so I never need to search for duplicates — I only need to compare each element to the last one I've confirmed as unique, which is the classic slow/fast two-pointer pattern: fast_pointer scans ahead through every element, and slow_pointer marks the next position where a genuinely new unique value should be written. Whenever nums[fast_pointer] differs from the most recently confirmed unique value (nums[slow_pointer - 1]), I copy it into place at slow_pointer and advance that pointer; matching values are simply skipped over by fast_pointer without any write. I chose in-place two pointers over building a separate deduplicated list because the problem explicitly requires in-place modification with O(1) extra space, and a second array would trade that requirement away for no actual benefit, since sortedness already guarantees I never need to overwrite data I haven't read yet. This runs in O(n) time, since fast_pointer makes a single linear pass over the array, and O(1) space, since only two integer pointers are tracked regardless of input size."""